// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/glass-theme/FrostedDepth.tsx": () => import("../components/mockups/glass-theme/FrostedDepth.tsx"),
  "./components/mockups/glass-theme/LiquidAurora.tsx": () => import("../components/mockups/glass-theme/LiquidAurora.tsx"),
  "./components/mockups/glass-theme/VisionProGlass.tsx": () => import("../components/mockups/glass-theme/VisionProGlass.tsx")
};
